### ISSUE TITLE
executing a transaction that contain hive query , throw exception

### ISSUE THREAD

**Issue by tangjx** [it4biz/kettle-web-integrator#1]
Caused by: org.pentaho.di.core.exception.KettleDatabaseException: 
database type with plugin id [HIVE2] couldn't be found!

**Comment by caiomsouza** [comment]
Hi Tangjx,

Thanks for your feedback about running HIVE2.

It is probably not working because we did not put all the plug-ins in the lib of the projects.

Could you fix it and send us a pull request?

In the next weeks we will be focus in others features for the project so we will not be able to working on this.

But, again, thanks a lot for your help.

Best Regards,

Caio

**Comment by caiomsouza** [comment]
We are working on the issues:

https://github.com/it4biz/kettle-web-integrator/issues/2
https://github.com/it4biz/kettle-web-integrator/issues/3
https://github.com/it4biz/kettle-web-integrator/issues/4

Feel free to help us test it when it is ready.

Best Regards,

Caio

**Comment by caiomsouza** [comment]
We will have to work on the issue 6, it is the probably the same problem you have.

https://github.com/it4biz/kettle-web-integrator/issues/6

When we finish this plugin problem it will work for Hive, too.

**Comment by fernandommota** [comment]
Hello @tangjx,

Please, update your repository from last version and copy the entire folder of plugin to kettle/system/plugins.

https://github.com/it4biz/kettle-web-integrator/blob/master/README.md#usage

**Comment by tangjx** [comment]
@caiomsouza @fernandommota Hey Caiomsouza and Fernandommota,

Thank you for fix this problem. I'm so sorry, It's a long time that i have no time for github.  
I have integrated kettle in my own web project, and becase this project is owned by my company , it cann't submit to github.  but I will follow your kettle-web-integrator project all the time. if i can do some contribution for this project, i want to, thank you!

**Comment by caiomsouza** [comment]
Hi @tangjx,

I happy for you.

If you need anything tell me.

Testing our software is enough for us, feel free to help.

**Comment by zsie000** [comment]
Hi ,
database type with plugin id [HIVE2] couldn't be found!
here i am using HIVE2 .i have all the plugins in the lib also to execute it .i am using data integration 8.0.0.0-28.jar version

The problem is ,this error is not throwing all the time.it is throwing on and often. If it is because of any plugin missing ,how could it be executing the time when without throwing any error. 


can anyone help me out here .
